# Generated by Django 4.2.6 on 2023-11-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docs', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='delta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_joining',
            field=models.DateField(null=True),
        ),
    ]
