# Generated by Django 4.2.6 on 2023-10-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docs', '0004_alter_users_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='enrollment_no',
            field=models.BigIntegerField(default=10),
        ),
    ]
